### ISSUE TITLE
`reclaim-mannequin --skip-invitation` option cannot be used in non-interactive environment

### ISSUE THREAD

**Issue by kmaehashi** [github/gh-gei#1011]
`reclaim-mannequin --skip-invitation` command cannot be used in non-interactive environment, as it requires to respond with console for `Are you sure you wish to continue? (y/n)` question. It would be great if `--yes` option is provided.

Redirecting `yes` didn't work either:

```
$ yes | gh gei reclaim-mannequin <snip> --skip-invitation
<snip>
[2023-06-01 05:32:35] [INFO] Reclaiming Mannequins with CSV...
Reclaiming mannequins with the --skip-invitation option is immediate and irreversible. Are you sure you wish to continue? (y/n)
[2023-06-01 05:32:35] [ERROR] An unexpected error happened. Please see the logs for details.
```

The verbose log says:
```
<snip>
[2023-06-01 05:32:35] [INFO] Reclaiming Mannequins with CSV...
[2023-06-01 05:32:35] [ERROR] System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean )
   at System.Console.ReadKey(Boolean )
   at OctoshiftCLI.Services.ConfirmationService.ReadKey()
   at OctoshiftCLI.Services.ConfirmationService.AskForConfirmation(String confirmationPrompt, String cancellationErrorMessage)
   at OctoshiftCLI.Commands.ReclaimMannequin.ReclaimMannequinCommandHandler.Handle(ReclaimMannequinCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.RunHandler[TArgs,THandler](TArgs args, ServiceProvider sp, CommandBase`2 command)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by dylan-smith** [comment]
great feedback! There's a follow-up PR in progress to improve this feature where somebody else mentioned something similar: https://github.com/github/gh-gei/pull/1006

**Comment by kmaehashi** [comment]
Ah great, glad to know the improvement is ongoing! I should have to search first 😅
