### ISSUE TITLE
Archive generation fails

### ISSUE THREAD

**Issue by adnansakel** [github/gh-gei#1038]
## Description
Getting following error while attempting migrating a single repository from github enterprise server. I am using aws s3 bucket as blob storage configured on github management console. The github enterprise version is 3.8.3  

```
[ERROR] OctoshiftCLI.OctoshiftCliException: Archive generation failed for id: 6461
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.WaitForArchiveGeneration(GithubApi githubApi, String githubSourceOrg, Int32 archiveId)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.GenerateArchive(String githubSourceOrg, String sourceRepo, Boolean skipReleases, Boolean lockSourceRepo)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.<>c__DisplayClass20_0.<<GenerateAndUploadArchive>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at OctoshiftCLI.RetryPolicy.Retry[T](Func`1 func)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.GenerateAndUploadArchive(String githubSourceOrg, String sourceRepo, String awsBucketName, Boolean skipReleases, Boolean lockSourceRepo, Boolean blobCredentialsRequired, Boolean keepArchive)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.RunHandler[TArgs,THandler](TArgs args, ServiceProvider sp, CommandBase`2 command)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```
   ## Following is the command
   ```
   gh gei migrate-repo --github-source-org "my_org" --source-repo "my_repo" --github-target-org "my_target_org" --target-repo "my_repo" --ghes-api-url "https://GHES_URL/api/v3" --no-ssl-verify
   ```

**Comment by timrogers** [comment]
Hi there! 👋 Thanks for reaching out and I’m sorry to hear you’re having issues with exports on your Enterprise Server. 

This is an issue with Enterprise Server rather than with this open source CLI, so I’m going to close this issue and ask you to submit a GitHub Support ticket instead. 

When you create that issue, could you please include a support bundle for your server? If you’re not sure how to do that, support will be able to assist.
