### ISSUE TITLE
GitHub Enterprise Importer is currently unavailable

### ISSUE THREAD

**Issue by rakeshdoddi3646** [github/gh-gei#1109]
We are migrating repos from BitBucket to Github enterprise server and having issues while doing that.

Please find the error log and if someone can help us on this would be great

```
[2023-09-01 10:04:02] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":null},"errors":[{"type":"SERVICE_UNAVAILABLE","path":["createMigrationSource"],"locations":[{"line":1,"column":109}],"message":"GitHub Enterprise Importer is currently unavailable. Please try again later."}]}
[2023-09-01 10:04:02] [ERROR] OctoshiftCLI.OctoshiftCliException: GitHub Enterprise Importer is currently unavailable. Please try again later.
at OctoshiftCLI.Services.GithubClient.EnsureSuccessGraphQLResponse(JObject response) in /home/rdoddi/gh-gei/src/Octoshift/Services/GithubClient.cs:line 255
at OctoshiftCLI.Services.GithubClient.PostGraphQLAsync(String url, Object body, Dictionary2 customHeaders) in /home/rdoddi/gh-gei/src/Octoshift/Services/GithubClient.cs:line 75 at OctoshiftCLI.Services.GithubApi.CreateBbsMigrationSource(String orgId) in /home/rdoddi/gh-gei/src/Octoshift/Services/GithubApi.cs:line 308 at OctoshiftCLI.BbsToGithub.Commands.MigrateRepo.MigrateRepoCommandHandler.ImportArchive(MigrateRepoCommandArgs args, String archiveUrl) in /home/rdoddi/gh-gei/src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:line 208 at OctoshiftCLI.BbsToGithub.Commands.MigrateRepo.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args) in /home/rdoddi/gh-gei/src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:line 102 at OctoshiftCLI.Extensions.CommandExtensions.RunHandler[TArgs,THandler](TArgs args, ServiceProvider sp, CommandBase2 command) in /home/rdoddi/gh-gei/src/Octoshift/Extensions/CommandExtensions.cs:line 65
at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<b__0>d.MoveNext() in /home/rdoddi/gh-gei/src/Octoshift/Extensions/CommandExtensions.cs:line 51
--- End of stack trace from previous location --- 
```

For more information we are trying to call the graphql api, mutation end point createMigrationSource and getting the error

Current Github enterprise version that I am using is 3.9.3

**Comment by timrogers** [comment]
@rakeshdoddi3646 Thanks for flagging this! I've just tried running a migratin myself, and it seems to be working okay for me. Can you try again now?

**Comment by rakeshdoddi3646** [comment]
@timrogers thanks for responding o this can I know what  github enterprise server version you are using?
