### ISSUE TITLE
Unable to run gh gei migrate-repo 

### ISSUE THREAD

**Issue by rakeshdoddi3646** [github/gh-gei#1213]
Hello 

I am using gh gei tool to migrate repositories from GitHub Enterprise Server to GitHub EMU cloud but while executing the script I am getting bellow error.

[2024-01-25 20:31:28] [INFO] Waiting for archive with id 115 generation to finish. Current status: failed
[2024-01-25 20:31:28] [DEBUG] OctoshiftCLI.OctoshiftCliException: Archive generation failed for id: 115
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.WaitForArchiveGeneration(GithubApi githubApi, String githubSourceOrg, Int32 archiveId)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.GenerateArchive(String githubSourceOrg, String sourceRepo, Boolean skipReleases, Boolean lockSourceRepo)
   at OctoshiftCLI.GithubEnterpriseImporter.Commands.MigrateRepo.MigrateRepoCommandHandler.<>c__DisplayClass21_0.<<GenerateAndUploadArchive>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
[2024-01-25 20:31:28] [DEBUG] Retrying...

Can someone please help me with this?

Command that I am executing 

gh gei migrate-repo --github-source-org <SourceOrg>--source-repo <SourceRepo>--github-target-org <targetOrg> --target-repo <TargetRepo> --ghes-api-url <url> --aws-bucket-name <bucketname>

**Comment by timrogers** [comment]
Closing as we'll need to handle this through GitHub Support
