### ISSUE TITLE
integrate-boards throws NullReferenceException

### ISSUE THREAD

**Issue by dw-alexangas** [github/gh-gei#1251]
## Description

Running the command:

`gh ado2gh integrate-boards --ado-org "ORGNAME" --ado-team-project "Project Name" --github-org "_GitHub Org Name_" --github-repo "_GitHub Repo Name_"`

Fails with:

```
[2024-06-19 13:40:59] [INFO] Integrating Azure Boards...
[2024-06-19 13:40:59] [DEBUG] HTTP GET: https://dev.azure.com/ORGNAME/_apis/projects/Project%20Name?api-version=5.0-preview.1
[2024-06-19 13:40:59] [DEBUG] RESPONSE (OK): {"id":"GUID","name":"Project Name","description":"","url":"https://dev.azure.com/ORGNAME/_apis/projects/GUID","collection":{"id":"GUID","name":"ORGNAME","url":"https://dev.azure.com/ORGNAME/_apis/projectCollections/GUID","collectionUrl":"https://dev.azure.com/ORGNAME/"},"state":"wellFormed","defaultTeam":{"id":"GUID","name":"Team Name","url":"https://dev.azure.com/ORGNAME/_apis/projects/GUID/teams/GUID"},"revision":493,"capabilities":{"processTemplate":{"templateName":"Basic","templateTypeId":"b8a3a935-7e91-48b8-a94c-606d37c3e9f2"},"versioncontrol":{"sourceControlType":"Git","gitEnabled":"True","tfvcEnabled":"False"}},"visibility":"private","lastUpdateTime":"0001-01-01T00:00:00"}
[2024-06-19 13:40:59] [DEBUG] HTTP POST: https://dev.azure.com/ORGNAME/_apis/Contribution/HierarchyQuery?api-version=5.0-preview.1
[2024-06-19 13:41:00] [DEBUG] HTTP BODY: {"contributionIds":["ms.vss-work-web.github-user-data-provider"],"dataProviderContext":{"properties":{"accessToken":"***","sourcePage":{"routeValues":{"project":"Project Name"}}}}}
[2024-06-19 13:41:00] [DEBUG] RESPONSE (OK): {"dataProviderSharedData":{},"dataProviders":{"ms.vss-web.component-data":{},"ms.vss-web.shared-data":null}}
[2024-06-19 13:41:00] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object.
   at OctoshiftCLI.Services.AdoApi.GetGithubHandle(String org, String teamProject, String githubToken)
   at OctoshiftCLI.AdoToGithub.Commands.IntegrateBoards.IntegrateBoardsCommandHandler.Handle(IntegrateBoardsCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.RunHandler[TArgs,THandler](TArgs args, ServiceProvider sp, CommandBase`2 command)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

## Reproduction Steps

As above, using:

* ADO Token with Full Access
* GitHub classic token with admin:org, repo, workflow
* gh version 2.51.0 (2024-06-13)
* ado2gh CLI [v1.8.0]

**Comment by ArinGhazarian** [comment]
👋 thanks for filing an issue. So the problem here is the ADO token, it needs to have access to **all organizations** otherwise the `integrate-boards` command won't work.

**Comment by dylan-smith** [comment]
It’s needs more than just Full Access it also needs the All Orgs setting on the token.



![Image](https://github.com/user-attachments/assets/d4f17f4c-44e4-4135-aa43-e5031e09150b)

**Comment by dylan-smith** [comment]
Best way to get additional help is to create a GitHub support ticket. Not sure off the top of my head why this would happen.
