### ISSUE TITLE
Unhandled exception with blank environment variables

### ISSUE THREAD

**Issue by digimangos** [github/gh-gei#274]
## Description

Unhandled exception: System.ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
   at System.String.Replace(String oldValue, String newValue)
   at OctoshiftCLI.OctoLogger.MaskSecrets(String msg)
   at OctoshiftCLI.OctoLogger.LogError(Exception ex)
   at OctoshiftCLI.AdoToGithub.Program.<>c.<BuildParser>b__2_0(Exception ex, InvocationContext _)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

## Reproduction Steps

I'm using ado2gh, and received the following exception because my environment variables were set as empty strings.

**Comment by dylan-smith** [comment]
I'm trying to reproduce this error so I can give some advice on testing, but I'm struggling to repro it.

What command were you running to get this error?

**Comment by digimangos** [comment]
Hi @dylan-smith, basically if you do something like:

```
export ADO_PAT=""
./ado2gh migrate-repo --ado-org xxx --ado-team-project xxx --ado-repo xxx --github-org xxx --github-repo xxx
```

In the previous build you should see the error, and after my change you should get the message that:
`ADO_PAT environment variable is not set.`

🤞
