### ISSUE TITLE
Error trying to migrate with v 0.9 of ado2gh migrate-repo

### ISSUE THREAD

**Issue by DaveKLloyd** [github/gh-gei#422]
## Description

Tried to run a migration today for the first time in a while and I'm getting errors. 

Running v0.9 of ado2gh.exe

looks like it's complaining about an AccessToken. my GH_PAT and ADO_PAT are there and both work for other scripts. 

**Command is:** 
``` 
ado2gh migrate-repo --ado-org "$ado_orgname" --ado-team-project "$ado_project" --ado-repo "$ado_repo" --github-org "$gh_orgname" --github-repo "$gh_repo"
```
**Here is in the verbose.log:**
```
[1:06 PM] [INFO] Migrating Repo...
[1:06 PM] [INFO] ADO ORG: fusionfabric
[1:06 PM] [INFO] ADO TEAM PROJECT: InigoMontoya
[1:06 PM] [INFO] ADO REPO: chassis-app
[1:06 PM] [INFO] GITHUB ORG: finastra-platform
[1:06 PM] [INFO] GITHUB REPO: InigoMontoya-chassis-app
[1:06 PM] [DEBUG] HTTP POST: https://api.github.com/graphql
[1:06 PM] [DEBUG] HTTP BODY: {"query":"query($login: String!) {organization(login: $login) { login, id, name } }","variables":{"login":"finastra-platform"}}
[1:06 PM] [DEBUG] RESPONSE (OK): {"data":{"organization":{"login":"finastra-platform","id":"O_kgDOBZViIw","name":"finastra-platform"}}}
[1:06 PM] [DEBUG] HTTP POST: https://api.github.com/graphql
[1:06 PM] [DEBUG] HTTP BODY: {"query":"mutation createMigrationSource($name: String!, $url: String!, $ownerId: ID!, $accessToken: String!, $type: MigrationSourceType!, $githubPat: String) { createMigrationSource(input: {name: $name, url: $url, ownerId: $ownerId, accessToken: $accessToken, type: $type, githubPat: $githubPat}) { migrationSource { id, name, url, type } } }","variables":{"name":"Azure DevOps Source","url":"https://dev.azure.com","ownerId":"O_kgDOBZViIw","type":"AZURE_DEVOPS","accessToken":"***","githubPat":"***"},"operationName":"createMigrationSource"}
[1:06 PM] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":{"migrationSource":{"id":"MS_kgC4NjI5NzljODE1YmNlNTEwMDA4OGI1YWY0","name":"Azure DevOps Source","url":"https://dev.azure.com","type":"AZURE_DEVOPS"}}}}
[1:06 PM] [DEBUG] HTTP POST: https://api.github.com/graphql
[1:06 PM] [DEBUG] HTTP BODY: {"query":"mutation startRepositoryMigration($sourceId: ID!, $ownerId: ID!, $sourceRepositoryUrl: URI!, $repositoryName: String!, $continueOnError: Boolean!, $gitArchiveUrl: String!, $metadataArchiveUrl: String!) { startRepositoryMigration(input: { sourceId: $sourceId, ownerId: $ownerId, sourceRepositoryUrl: $sourceRepositoryUrl, repositoryName: $repositoryName, continueOnError: $continueOnError, gitArchiveUrl: $gitArchiveUrl, metadataArchiveUrl: $metadataArchiveUrl }) { repositoryMigration { id, migrationSource { id, name, type }, sourceUrl, state, failureReason } } }","variables":{"sourceId":"MS_kgC4NjI5NzljODE1YmNlNTEwMDA4OGI1YWY0","ownerId":"O_kgDOBZViIw","sourceRepositoryUrl":"https://dev.azure.com/fusionfabric/InigoMontoya/_git/chassis-app","repositoryName":"InigoMontoya-chassis-app","continueOnError":true,"gitArchiveUrl":"","metadataArchiveUrl":""},"operationName":"startRepositoryMigration"}
[1:06 PM] [DEBUG] RESPONSE (OK): {"errors":[{"path":["mutation startRepositoryMigration","startRepositoryMigration","input","accessToken"],"extensions":{"code":"missingRequiredInputObjectAttribute","argumentName":"accessToken","argumentType":"String!","inputObjectType":"StartRepositoryMigrationInput"},"locations":[{"line":1,"column":237}],"message":"Argument 'accessToken' on InputObject 'StartRepositoryMigrationInput' is required. Expected type String!"}]}
[1:06 PM] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object.
   at OctoshiftCLI.GithubApi.StartMigration(String migrationSourceId, String adoRepoUrl, String orgId, String repo, String gitArchiveUrl, String metadataArchiveUrl)
   at OctoshiftCLI.AdoToGithub.Commands.MigrateRepoCommand.Invoke(String adoOrg, String adoTeamProject, String adoRepo, String githubOrg, String githubRepo, Boolean ssh, Boolean verbose)
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by DaveKLloyd** [comment]
Grabbed version 0.17 and it worked. 

Can someone explain this?
