### ISSUE TITLE
Errors calling ado2gh rewire-pipeline

### ISSUE THREAD

**Issue by DaveKLloyd** [github/gh-gei#452]
## Description

Attempted to migrate a repo today from Azure DevOps to GitHub and got errors below. 

The Call:
ado2gh rewire-pipeline --ado-org "ADO_ORG" --ado-team-project "PROJECT" --ado-pipeline "PIPELINE" --github-org "GH_ORG" --github-repo "GH_REPO" --service-connection-id "CONN_ID"

## Log
```
[1:05 PM] [INFO] You are running the latest version of the ado2gh CLI [v0.18]
[1:05 PM] [INFO] Rewiring Pipeline to GitHub repo...
[1:05 PM] [INFO] ADO ORG: ADO_ORG
[1:05 PM] [INFO] ADO TEAM PROJECT: PROJECT
[1:05 PM] [INFO] ADO PIPELINE: PIPELINES
[1:05 PM] [INFO] GITHUB ORG: GH_ORG
[1:05 PM] [INFO] GITHUB REPO: GH_REPO
[1:05 PM] [INFO] SERVICE CONNECTION ID: 2e165bd1-35c0-4ec1-9cd1-88c9fde8a8f8
[1:05 PM] [DEBUG] HTTP GET: https://dev.azure.com/ADO_ORG/PROJECT/_apis/build/definitions
[1:05 PM] [DEBUG] RESPONSE (OK): {"count":7,"value":[{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1386?revision=3"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=1386"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=1386&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/1386"}},"quality":"definition","authoredBy":{"displayName":"David LLoyd","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/e4d2cd97-d5e2-6c92-aa1c-1d9ca8ce579b","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTRkMmNkOTctZDVlMi03YzkyLWFhMWMtMWQ5Y2E4Y2U1Nzli"}},"id":"e4d2cd97-d5e2-6c92-aa1c-1d9ca8ce579b","uniqueName":"David.LLoyd@dh.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTRkMmNkOTctZDVlMi03YzkyLWFhMWMtMWQ5Y2E4Y2U1Nzli","descriptor":"aad.ZTRkMmNkOTctZDVlMi03YzkyLWFhMWMtMWQ5Y2E4Y2U1Nzli"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/557"}},"id":557,"name":"Default","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/557","pool":{"id":1,"name":"Default"}},"id":1386,"name":"garbage_collector","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1386?revision=3","uri":"vstfs:///Build/Definition/1386","path":"\\","type":"build","queueStatus":"enabled","revision":3,"createdDate":"2022-02-07T13:28:27.983Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1397?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=1397"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=1397&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/1397"}},"quality":"definition","authoredBy":{"displayName":"Alexandre Feblot","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/e4852ff0-3670-60f0-8604-afb85146f7ef","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"}},"id":"e4852ff0-3670-60f0-8604-afb85146f7ef","uniqueName":"alexandre.feblot@finastra.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm","descriptor":"aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":1397,"name":"PIPELINES","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1397?revision=2","uri":"vstfs:///Build/Definition/1397","path":"\\Services","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2021-04-12T14:42:46.347Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1398?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=1398"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=1398&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/1398"}},"quality":"definition","authoredBy":{"displayName":"Alexandre Feblot","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/e4852ff0-3670-60f0-8604-afb85146f7ef","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"}},"id":"e4852ff0-3670-60f0-8604-afb85146f7ef","uniqueName":"alexandre.feblot@finastra.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm","descriptor":"aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":1398,"name":"PIPELINES-develop","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1398?revision=2","uri":"vstfs:///Build/Definition/1398","path":"\\Services-deployments","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2021-04-12T14:43:07.847Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1399?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=1399"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=1399&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/1399"}},"quality":"definition","authoredBy":{"displayName":"Alexandre Feblot","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/e4852ff0-3670-60f0-8604-afb85146f7ef","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"}},"id":"e4852ff0-3670-60f0-8604-afb85146f7ef","uniqueName":"alexandre.feblot@finastra.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm","descriptor":"aad.ZTQ4NTJmZjAtMzY3MC03MGYwLTg2MDQtYWZiODUxNDZmN2Vm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":1399,"name":"PIPELINES-master","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/1399?revision=2","uri":"vstfs:///Build/Definition/1399","path":"\\Services-deployments","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2021-04-12T14:43:37.967Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2587?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=2587"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=2587&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/2587"}},"quality":"definition","authoredBy":{"displayName":"Lukasz Cymanowski","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/b878f034-eb02-6c75-92a2-c5e05c0bec6f","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"}},"id":"b878f034-eb02-6c75-92a2-c5e05c0bec6f","uniqueName":"Lukasz.Cymanowski@dh.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm","descriptor":"aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":2587,"name":"fusion-analytics-product-recommender","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2587?revision=2","uri":"vstfs:///Build/Definition/2587","path":"\\Services","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2022-02-03T11:59:30.213Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2588?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=2588"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=2588&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/2588"}},"quality":"definition","authoredBy":{"displayName":"Lukasz Cymanowski","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/b878f034-eb02-6c75-92a2-c5e05c0bec6f","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"}},"id":"b878f034-eb02-6c75-92a2-c5e05c0bec6f","uniqueName":"Lukasz.Cymanowski@dh.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm","descriptor":"aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":2588,"name":"fusion-analytics-product-recommender-develop","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2588?revision=2","uri":"vstfs:///Build/Definition/2588","path":"\\Services-deployments","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2022-02-03T12:00:08.763Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}},{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2589?revision=2"},"web":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/definition?definitionId=2589"},"editor":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_build/designer?id=2589&_a=edit-build-definition"},"badge":{"href":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/status/2589"}},"quality":"definition","authoredBy":{"displayName":"Lukasz Cymanowski","url":"https://spsprodweu3.vssps.visualstudio.com/Af0a25e19-9892-4ecf-b06b-2883259395d6/_apis/Identities/b878f034-eb02-6c75-92a2-c5e05c0bec6f","_links":{"avatar":{"href":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"}},"id":"b878f034-eb02-6c75-92a2-c5e05c0bec6f","uniqueName":"Lukasz.Cymanowski@dh.com","imageUrl":"https://dev.azure.com/ADO_ORG/_apis/GraphProfile/MemberAvatars/aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm","descriptor":"aad.Yjg3OGYwMzQtZWIwMi03Yzc1LTkyYTItYzVlMDVjMGJlYzZm"},"drafts":[],"queue":{"_links":{"self":{"href":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562"}},"id":562,"name":"Hosted Ubuntu 1604","url":"https://dev.azure.com/ADO_ORG/_apis/build/Queues/562","pool":{"id":11,"name":"Hosted Ubuntu 1604","isHosted":true}},"id":2589,"name":"fusion-analytics-product-recommender-master","url":"https://dev.azure.com/ADO_ORG/43e8bc4c-8407-455e-a36c-50c8cf69e599/_apis/build/Definitions/2589?revision=2","uri":"vstfs:///Build/Definition/2589","path":"\\Services-deployments","type":"build","queueStatus":"enabled","revision":2,"createdDate":"2022-02-03T12:00:58.683Z","project":{"id":"43e8bc4c-8407-455e-a36c-50c8cf69e599","name":"PROJECT","url":"https://dev.azure.com/ADO_ORG/_apis/projects/43e8bc4c-8407-455e-a36c-50c8cf69e599","state":"wellFormed","revision":845,"visibility":"private","lastUpdateTime":"2021-04-08T08:33:21.9Z"}}]}
[1:05 PM] [ERROR] System.Collections.Generic.KeyNotFoundException: The given key '(ADO_ORG, PROJECT, \PIPELINES)' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey )
   at OctoshiftCLI.AdoApi.GetPipelineId(String org, String teamProject, String pipeline)
   at OctoshiftCLI.AdoToGithub.Commands.RewirePipelineCommand.Invoke(String adoOrg, String adoTeamProject, String adoPipeline, String githubOrg, String githubRepo, String serviceConnectionId, String adoPat, Boolean verbose)
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by dylan-smith** [comment]
Is this command generated from a previous generate-script command, and if so what version of the CLI was used to generate the script?

**Comment by dylan-smith** [comment]
I think the ultimate fix is the pipeline name should be something like `\services\PIPELINES`, but generate-script should handle that for you, if it's not then there is a bug we need to fix.

**Comment by DaveKLloyd** [comment]
No this was generated a while back. I'll generate one and see what it gives me. The thing is I used generate script once a long time ago because I need to insert a bunch of other stuff in between your calls.

**Comment by dylan-smith** [comment]
there was a change done recently (I think in v0.18) where we realized that pipeline name is not unique enough. You can have 2 pipelines with the same name in different folders. So now rewire-pipeline takes the pipeline path, if you just give a name it assumes it's in the root folder.

**Comment by DaveKLloyd** [comment]
Thanks @dylan-smith for the quick response. 

Just checked out generate-script wow that is a lot different then the last time I ran it. :)
