### ISSUE TITLE
Getting a 401 trying to migrate a repo to github.

### ISSUE THREAD

**Issue by nfergusoncsc** [github/gh-gei#539]
First point, this is a github Enterprise Managed User instance.
I am attempting to migrate from Azure DevOps to the GitHub EMU instance.

I have created a service connection in ADO using a GitHub PAT. It has the appropriate access according to the documentation.

I've created a .csv file to do just one repo and was able to use the generate script flag successfully.
When I attempt to run the powershell script it generates I receive the 401 Unauthorized error on a Get command that attempts to get the repo on GitHub. 
I validated this does not pull back the repo:
GET: https://api.github.com/repos/CDT-temp/nferguson

The repo does exist:
![image](https://user-images.githubusercontent.com/77361729/182232733-b6974edf-a310-4aab-9186-a9ad66787b51.png)

[11:20 AM] [INFO] You are running the latest version of the ado2gh CLI [v0.22]
[11:20 AM] [INFO] Migrating Repo...
[11:20 AM] [INFO] ADO ORG: columbia1938
[11:20 AM] [INFO] ADO TEAM PROJECT: Delivery-Engineering
[11:20 AM] [INFO] ADO REPO: nferguson
[11:20 AM] [INFO] GITHUB ORG: CDT-temp
[11:20 AM] [INFO] GITHUB REPO: nferguson
[11:20 AM] [DEBUG] HTTP GET: https://api.github.com/repos/CDT-temp/nferguson
[11:20 AM] [DEBUG] GITHUB REQUEST ID: C87D:0E2F:D6BF1:E2A9B:62E8197E
[11:20 AM] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
[11:20 AM] [ERROR] System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OctoshiftCLI.GithubClient.SendAsync(HttpMethod httpMethod, String url, Object body, HttpStatusCode status)
   at OctoshiftCLI.GithubClient.GetAsync(String url)
   at OctoshiftCLI.GithubApi.RepoExists(String org, String repo)
   at OctoshiftCLI.AdoToGithub.Commands.MigrateRepoCommand.Invoke(String adoOrg, String adoTeamProject, String adoRepo, String githubOrg, String githubRepo, Boolean ssh, Boolean wait, String adoPat, String githubPat, Boolean verbose)
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by dylan-smith** [comment]
If you're getting a 401 it means the PAT your using for the target (GH_PAT) does not have the proper permissions. These are the scopes that the PAT requires: https://docs.github.com/en/early-access/github/migrating-with-github-enterprise-importer/running-a-migration-with-github-enterprise-importer/managing-access-for-github-enterprise-importer#required-scopes-for-personal-access-tokens

Not only that, but even if it did have proper permissions it looks like you'd probably get a different error, because if the repo already exists in the target you cannot migrate to it.

**Comment by nfergusoncsc** [comment]
Thank you, I can confirm I have those scopes on the gh PAT and then some. I initially tried it without the repo existing but then added one thinking it perhaps needed one. I'll remove and purge the repo and try again.

**Comment by nfergusoncsc** [comment]
I just gave the PAT massive access, in addition to the scopes in the docs and that worked. I apologize but I'm probably not able to say which one fixed it. I will just expire the token when I'm done.
