### ISSUE TITLE
Retries on GET against GHES

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#588]
We've seen a few failures in integration tests when reading from GHES. They seem to be transient errors. For GET's we should pretty much always have retry logic.

The most recent failure we saw was 
```
[2022-08-19T21:46:05.7112486+00:00] [INFO] Waiting for archive with id 5543 generation to finish. Current status: exporting
[2022-08-19T21:46:15.7075198+00:00] [DEBUG] HTTP GET: https://octoshift-ghe.westus2.cloudapp.azure.com/api/v3/orgs/e2e-testing-windows/migrations/5543
Error: 8-19T21:46:15.7655472+00:00] [ERROR] System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter , Memory`1 )
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|44_0()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at OctoshiftCLI.GithubClient.SendAsync(HttpMethod httpMethod, String url, Object body, HttpStatusCode status)
   at OctoshiftCLI.GithubClient.GetAsync(String url)
   at OctoshiftCLI.GithubApi.GetArchiveMigrationStatus(String org, Int32 migrationId)
```
https://github.com/github/gh-gei/runs/7926309135?check_suite_focus=true#step:18:4847

**Comment by dylan-smith** [comment]
Duplicate of #587
