### ISSUE TITLE
Retry on failure when polling for migration status

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#668]
If the API call to check the migration status fails (for any reason) we should retry that call. This scenario isn't covered by our existing retry logic because the existing retry logic applies to HTTP GET's, but the call to check migration status is a GQL endpoint so it is technically a POST and does not have retry logic today.

We also need to check the response payload to see if it failed, checking the HTTP status code isn't sufficient as GQL failures still return 200, with the error in the response body.

**Comment by timrogers** [comment]
Thanks to @synthead'd recent changes, this case is turning up quite a lot now. Here's an example log output: 

```
[14:07] [DEBUG] HTTP POST: https://api.github.com/graphql
[14:07] [DEBUG] HTTP BODY: {"query":"query($id: ID!) { node(id: $id) { ... on Migration { id, sourceUrl, migrationSource { name }, state, failureReason, repositoryName } } }","variables":{"id":"RM_kgDaACQxZmU1NTQ5Ny00OGY0LTQ4OGItOTRmNy03NWVkY2RlYmU3Y2Y"}}
[14:07] [DEBUG] GITHUB REQUEST ID: 0405:4886:2169D5B:441EE27:634853D4
[14:07] [DEBUG] RESPONSE (OK): {"data":{"node":null},"errors":[{"type":"SERVICE_UNAVAILABLE","path":["node"],"locations":[{"line":1,"column":19}],"message":"GitHub Enterprise Importer is currently unavailable. Please try again later."}]}
[14:07] [ERROR] System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at OctoshiftCLI.GithubApi.GetMigration(String migrationId)
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.Invoke(MigrateRepoCommandArgs args)
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I think we should prioritise this work to provide a smoother CLI experience.

@dylan-smith What do you think? How much of a lift would it be to implement these retries?

**Comment by timrogers** [comment]
> I actually started picking away at this on the weekend already. I should have a PR up soon.

Amazing! Thanks.

**Comment by tambling** [comment]
I see that #686 has been opened to close this — can I preemptively close https://github.com/github/migration-friction/issues/689, https://github.com/github/migration-friction/issues/699, and https://github.com/github/migration-friction/issues/701, assuming that this issue supersedes them (and will close soon)?
