### ISSUE TITLE
"HTTP ERROR 403" on download migration archive GHE server

### ISSUE THREAD

**Issue by rzheng7** [github/gh-gei#676]
## "HTTP ERROR 403" on download migration archive GHE server.  But I can download it manual with curl.

Could be a race condition https://sourcegraph.com/github.com/github/gh-gei@8e1ef90ccf2a42b0e24351df0426ac4c6c064483/-/blob/src/Octoshift/AzureApi.cs?L31-39?

* from 20221007140429.octoshift.verbose.log
```
  35   │ [2:04 PM] [INFO] Downloading archive from https://ghe-test.siriusxm.com/storage/migrations/29/archive/1032932e-d797-401d-afc3-e23bdf0c1ca3?token=AAAABEYIENZMMTOZW7PEI5TDICRHS
  36   │ [2:04 PM] [DEBUG] HTTP GET: https://ghe-test.siriusxm.com/storage/migrations/29/archive/1032932e-d797-401d-afc3-e23bdf0c1ca3?token=AAAABEYIENZMMTOZW7PEI5TDICRHS
  37   │ [2:04 PM] [DEBUG] RESPONSE (Forbidden): <truncated>
  38   │ [2:04 PM] [ERROR] [HTTP ERROR 403] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
  39   │    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
  40   │    at OctoshiftCLI.AzureApi.DownloadArchive(String fromUrl)
  41   │    at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.GenerateAndUploadArchive(String ghesApiUrl, String githubSourceOrg, String sourceRepo, String azureStorageConnectionString, String awsBucketName, String awsAccessKey, String awsSecretKey, String github
       │ SourcePat, Boolean skipReleases, Boolean lockSourceRepo, Boolean noSslVerify)
```
* manually download 
```
❯ http https://ghe-test.siriusxm.com/storage/migrations/29/archive/1032932e-d797-401d-afc3-e23bdf0c1ca3\?token\=AAAABEYIENZMMTOZW7PEI5TDICRHS
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 13134
Content-Security-Policy: default-src 'none'
Content-Type: application/x-gzip
Date: Fri, 07 Oct 2022 21:15:29 GMT
ETag: "cc39245da0d1af6e71475bf8240b04b95bafa9e91f63512b7e7082cbc1a7982c"
Last-Modified: Fri, 07 Oct 2022 21:04:41 GMT
Server: GitHub.com
Strict-Transport-Security: max-age=31557600
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-GitHub-Request-Id: 2b5d68e1-4685-11ed-80b9-58651b5897f1
X-XSS-Protection: 1; mode=block
timing-allow-origin: https://ghe-test.siriusxm.com



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

* local version
```
❯ gh version
gh version 2.17.0 (2022-10-04)
https://github.com/cli/cli/releases/tag/v2.17.0
❯ gh ext list
gh gei  github/gh-gei  v0.27
```

## Reproduction Steps on MacOS
```
1. gh gei generate-script --github-source-org ${SOURCE_ORG} --github-target-org ${DESTINATION_ORG} --download-migration-logs --output ${FILENAME}.ps1 --no-ssl-verify --ghes-api-url ${GHES_API_URL} --azure-storage-connection-string "${AZURE_STORAGE_CONNECTION_STRING}"
1. chmod +x ${FILENAME}.ps1 
2. ./${FILENAME}.ps1 
```

**Comment by rzheng-sxm** [comment]
AWS WAF rejected the request due to `NoUserAgent_HEADER`.  We are able to download the migration archive after AWS WAF rule adjusted.

**Comment by dylan-smith** [comment]
@rzheng-sxm thanks for reporting this, I'm wondering if there's anything we can do on the CLI side to improve things here. I had thought we were always setting a UserAgent header in all HTTP calls, however I see that for calls to API's we always explicitly set a custom UserAgent, but for the call to download this file we're just leaving the default (which I didn't think was blank, but perhaps it is).

I'm going to leave this open so we can revisit it when we have some time to see if we can improve things here.

**Comment by rzheng-sxm** [comment]
Thanks Dylan.

From: Dylan Smith ***@***.***>
Date: Wednesday, October 19, 2022 at 2:44 PM
To: github/gh-gei ***@***.***>
Cc: Zheng, Rong ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [github/gh-gei] "HTTP ERROR 403" on download migration archive GHE server (Issue #676)

@rzheng-sxm<https://urldefense.com/v3/__https:/github.com/rzheng-sxm__;!!NUnUjx3wvH5xgA!aMQRACutiAcvFNrvHGPyBf5xunAhBGbasK73V-ROhtn__3uprgS75eUesw3MN7oyoYFKeO8-ndCLuTkYkbzHUXhtADg$> thanks for reporting this, I'm wondering if there's anything we can do on the CLI side to improve things here. I had thought we were always setting a UserAgent header in all HTTP calls, however I see that for calls to API's we always explicitly set a custom UserAgent, but for the call to download this file we're just leaving the default (which I didn't think was blank, but perhaps it is).

I'm going to leave this open so we can revisit it when we have some time to see if we can improve things here.
