### ISSUE TITLE
Error migrating big size repos

### ISSUE THREAD

**Issue by datenciadedalus** [github/gh-gei#691]
## Description

I'm trying to migrate a repo with 733mb which takes a long long time... and then getting an error 

```
[08:16] [ERROR] OctoshiftCLI.OctoshiftCliException: Git source migration failed. Error message: undefined local variable or method `download_retries' for #<FileDownloader:0x00007ff8c20d7bc8>
```

The error is produced by the `gh gei wait-for-migration` command (included in the generated powershell script)

```
...
[08:16] [INFO] Waiting 10 seconds...
[08:16] [DEBUG] HTTP POST: https://api.github.com/graphql
...
[08:16] [INFO] Waiting 10 seconds...
[08:16] [DEBUG] HTTP POST: https://api.github.com/graphql
...
[08:16] [ERROR] Migration ***** failed for REPO_NAME
[08:16] [ERROR] OctoshiftCLI.OctoshiftCliException: Git source migration failed. Error message: undefined local variable or method `download_retries' for #<FileDownloader:0x00007ff8c20d7bc8>
Did you mean?  download_attempt
   at OctoshiftCLI.Handlers.WaitForMigrationCommandHandler.WaitForRepositoryMigration(String migrationId, String githubPat, GithubApi githubApi)
   at OctoshiftCLI.Handlers.WaitForMigrationCommandHandler.Handle(WaitForMigrationCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by dylan-smith** [comment]
Hi @datenciadedalus , the best way to get help with this is to create a GitHub support ticket. This particular failure doesn't appear to be the result of any CLI bug (and this OSS repo is for the CLI part of the migration tools only).
