### ISSUE TITLE
HttpDownloadService dies on large files

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#746]
## Description

If the GHES archive that HttpDownloadService tries to download is > 2GB the CLI will crash.

```
[11:16 PM] [ERROR] [HTTP ERROR ] System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at OctoshiftCLI.HttpDownloadService.DownloadToBytes(String url)
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.GenerateAndUploadArchive(String githubSourceOrg, String sourceRepo, String awsBucketName, Boolean skipReleases, Boolean lockSourceRepo)
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

We probably need to do some kind of streaming of the response instead of trying to read the whole thing into memory all at once.

**Comment by timrogers** [comment]
Kinda surprised by this one, as I thought that another known issue in GHES meant that archives larger than 1GB couldn't be generated successfully. Moving this down in the backlog until we figure it out.

**Comment by timrogers** [comment]
@hfishback01 Am I right that you're going to be working on this one soon? ❤

**Comment by hfishback01** [comment]
@timrogers working on it currently :) Dylan came up with the idea, I'm implementing and testing it. 

FYI it's taking a bit longer because the `copyToAsync` method used [here](https://github.com/github/gh-gei/compare/main...downloading-large-files#diff-20408566f38e86271a5d0dee76e29f1e6754f3a3537840a2efa42b64b54db7c3R34) takes between 20-30min to run on my machine (it did not take this long on Dylan's) so I'm trying to figure out if this is isolated to my machine or not.

**Comment by timrogers** [comment]
Wonderful! Thank you.
