### ISSUE TITLE
Incomplete URL escaping

### ISSUE THREAD

**Issue by digimangos** [github/gh-gei#772]
## Description

Raising this as a result of migration friction. My client is migrating from ADO to GitHub using the ado2gh CLI extension. They have a project name which contains brackets, e.g. `Knowledge Management (KM)`. When parsing this project to `ado2gh` the migration fails with the following error:

```bash
[17:11] [ERROR] The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.
```

If you parse in the value to `ado2gh` with the project name URL escaped as `Knowledge Management %28KM%29` then the migration completes successfully.

Presumably the fix is to change the logic in `MigrateRepoCommandHandler.cs` at line 101:

```dotnet
  private string GetAdoRepoUrl(string org, string project, string repo) => $"https://dev.azure.com/{org}/{project}/_git/{repo}".Replace(" ", "%20");
```

Although more pervasive changes might be required as other commands may be affected

## Reproduction Steps
- In Azure create a project name containing brackets i.e. `Knowledge Management (KM)`
- Use this project name as an input to `ado2gh`.
- See failure:
  ```bash
  ➜  ~ gh ado2gh migrate-repo --ado-org digimangos --ado-team-project "Knowledge Management (KM)" --ado-repo test-repo --github-org digimangos-work-dev --github-repo com.digimangos.bracket-test-2 --wait --ado-pat xxx --github-pat xxx --verbose
  \[10:53] [INFO] You are running the latest version of the ado2gh CLI [v0.31]
  [10:53] [INFO] Migrating Repo...
  [10:53] [INFO] ADO ORG: digimangos
  [10:53] [INFO] ADO TEAM PROJECT: Knowledge Management (KM)
  [10:53] [INFO] ADO REPO: test-repo
  [10:53] [INFO] GITHUB ORG: digimangos-work-dev
  [10:53] [INFO] GITHUB REPO: com.digimangos.bracket-test-2
  [10:53] [INFO] WAIT: true
  [10:53] [INFO] ADO PAT: ***
  [10:53] [INFO] GITHUB PAT: ***
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"query($login: String!) {organization(login: $login) { login, id, name } }","variables":{"login":"digimangos-work-dev"}}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC359F:4DDC105:63BD439D
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"organization":{"login":"digimangos-work-dev","id":"O_kgDOBkvtQA","name":"digimangos-work-dev"}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"mutation createMigrationSource($name: String!, $url: String!, $ownerId: ID!, $type: MigrationSourceType!) { createMigrationSource(input: {name: $name, url: $url, ownerId: $ownerId, type: $type}) { migrationSource { id, name, url, type } } }","variables":{"name":"Azure DevOps Source","url":"https://dev.azure.com","ownerId":"O_kgDOBkvtQA","type":"AZURE_DEVOPS"},"operationName":"createMigrationSource"}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC36EC:4DDC28C:63BD439D
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":{"migrationSource":{"id":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","name":"Azure DevOps Source","url":"https://dev.azure.com","type":"AZURE_DEVOPS"}}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"\n                mutation startRepositoryMigration(\n                    $sourceId: ID!,\n                    $ownerId: ID!,\n                    $sourceRepositoryUrl: URI!,\n                    $repositoryName: String!,\n                    $continueOnError: Boolean!,\n                    $gitArchiveUrl: String,\n                    $metadataArchiveUrl: String,\n                    $accessToken: String!,\n                    $githubPat: String,\n                    $skipReleases: Boolean,\n                    $lockSource: Boolean) { \n                startRepositoryMigration(\n                    input: { \n                        sourceId: $sourceId,\n                        ownerId: $ownerId,\n                        sourceRepositoryUrl: $sourceRepositoryUrl,\n                        repositoryName: $repositoryName,\n                        continueOnError: $continueOnError,\n                        gitArchiveUrl: $gitArchiveUrl,\n                        metadataArchiveUrl: $metadataArchiveUrl,\n                        accessToken: $accessToken,\n                        githubPat: $githubPat,\n                        skipReleases: $skipReleases,\n                        lockSource: $lockSource\n                    }\n                ) {\n                    repositoryMigration {\n                        id,\n                        migrationSource {\n                            id,\n                            name,\n                            type\n                        },\n                        sourceUrl,\n                        state,\n                        failureReason\n                    }\n                  } }","variables":{"sourceId":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","ownerId":"O_kgDOBkvtQA","sourceRepositoryUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","repositoryName":"com.digimangos.bracket-test-2","continueOnError":true,"gitArchiveUrl":null,"metadataArchiveUrl":null,"accessToken":"***","githubPat":"***","skipReleases":false,"lockSource":false},"operationName":"startRepositoryMigration"}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC3F83:4DDCB17:63BD439F
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"startRepositoryMigration":{"repositoryMigration":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY","migrationSource":{"id":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","name":"Azure DevOps Source","type":"AZURE_DEVOPS"},"sourceUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","state":"QUEUED","failureReason":""}}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"query($id: ID!) { node(id: $id) { ... on Migration { id, sourceUrl, migrationSource { name }, state, failureReason, repositoryName } } }","variables":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY"}}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC4F24:4DDDB07:63BD43A2
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"node":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY","sourceUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","migrationSource":{"name":"Azure DevOps Source"},"state":"FAILED","failureReason":"The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.","repositoryName":"com.digimangos.bracket-test-2"}}}
  [10:53] [ERROR] Migration Failed. Migration ID: RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY
  [10:53] [ERROR] OctoshiftCLI.OctoshiftCliException: The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.
     at OctoshiftCLI.AdoToGithub.Handlers.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
     at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
  ```

**Comment by dylan-smith** [comment]
Thanks for reporting this. This definitely looks like a bug to me. We should probably use [proper URL encoding functions](https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.urlencode?view=net-7.0) instead of the pretty naïve "replace spaces with %20" we're doing now. I count at least 13 places in the code where we do this now that should all be updated.

**Comment by digimangos** [comment]
Hi @dylan-smith I did have a quick look in to this with the view to make PR fixing the issue, I think several of the cases are quickly fixed since they have the parameters which can be individually encoded. For example in:

```dotnet
        return $"{serverUrl}/{org}/{project}/_git/{repo}".Replace(" ", "%20");
```

You could just escape `org`, `project` and `repo` as part of the string interpolation and remove the `Replace` at the end. However... there are several other cases which have a URL already in them. e.g in `AdoClient.cs` at line [104](https://github.com/github/gh-gei/blob/3b2da2704e7c2d40405edc881fbea1260cafafa4/src/Octoshift/AdoClient.cs#L104). 

```dotnet
            var updatedUrl = url.Replace(" ", "%20");
```

Because obviously trying to encode at this point with the HttpUtility methods will end up encoding the colons and slashes like:

`http%3a%2f%2fdev.azure.com%2fmyorg%2fmyproject%2f_git%2fKnowledge%20Management%20%28KM%29`

The changes will need to be thought about more carefully to unpick where the encoding is happening (of course some of this string replacement may be duplicated because applying it to a string which has %20 already isn't currently an issue.
