### ISSUE TITLE
502 Bad Gateway can cause the migration to halt

### ISSUE THREAD

**Issue by testworksau** [github/gh-gei#781]
## Description

We attempted to run a trial migration over the weekend via the CLI (v0.31); it got ~4 hours into queuing repos and failed with:

```
[9:16 pm] [INFO] You are running the latest version of the gei CLI [v0.31]
[9:16 pm] [INFO] Migrating Repo...
[9:16 pm] [INFO] GITHUB SOURCE ORG:<ourorg>
[9:16 pm] [INFO] SOURCE REPO: <repo>
[9:16 pm] [INFO] GITHUB TARGET ORG: <ourorg>-target-trial-2
[9:16 pm] [INFO] TARGET REPO: <repo>
[9:16 pm] [ERROR] An unexpected error happened. Please see the logs for details.
```

The verbose logs show:

```
9:16 pm] [DEBUG] HTTP GET: https://raw.githubusercontent.com/github/gh-gei/main/LATEST-VERSION.txt
[9:16 pm] [DEBUG] RESPONSE (OK): v0.31

[9:16 pm] [INFO] You are running the latest version of the gei CLI [v0.31]
[9:16 pm] [INFO] Migrating Repo...
[9:16 pm] [INFO] GITHUB SOURCE ORG: <ourorg>
[9:16 pm] [INFO] SOURCE REPO: <repo>
[9:16 pm] [INFO] GITHUB TARGET ORG: <ourorg>-target-trial-2
[9:16 pm] [INFO] TARGET REPO: <repo>
[9:16 pm] [DEBUG] HTTP POST: https://api.github.com/graphql
[9:16 pm] [DEBUG] HTTP BODY: {"query":"query($login: String!) {organization(login: $login) { login, id, name } }","variables":{"login":"<ourorg>-target-trial-2"}}
[9:16 pm] [DEBUG] GITHUB REQUEST ID: F87D:52D2:159A400:16FBA90:63C12F78
[9:16 pm] [DEBUG] RESPONSE (OK): {"data":{"organization":{"login":"<ourorg>-target-trial-2","id":"O_kgDOB06WWA","name":"<ourorg>-target-trial-2"}}}
[9:16 pm] [DEBUG] HTTP POST: https://api.github.com/graphql
[9:16 pm] [DEBUG] HTTP BODY: {"query":"mutation createMigrationSource($name: String!, $url: String!, $ownerId: ID!, $type: MigrationSourceType!) { createMigrationSource(input: {name: $name, url: $url, ownerId: $ownerId, type: $type}) { migrationSource { id, name, url, type } } }","variables":{"name":"GHEC Source","url":"https://github.com","ownerId":"O_kgDOB06WWA","type":"GITHUB_ARCHIVE"},"operationName":"createMigrationSource"}
[9:16 pm] [DEBUG] GITHUB REQUEST ID: F87D:52D2:159A42B:16FBAB0:63C12F78
[9:16 pm] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":{"migrationSource":{"id":"MS_kgDaACRmMDBiZThhNS0zMzIyLTRkYzUtODliMS03Zjg1ZjExY2E2YWU","name":"GHEC Source","url":"https://github.com","type":"GITHUB_ARCHIVE"}}}}
[9:16 pm] [DEBUG] HTTP POST: https://api.github.com/graphql
[9:16 pm] [DEBUG] HTTP BODY: {"query":"\n                mutation startRepositoryMigration(\n                    $sourceId: ID!,\n                    $ownerId: ID!,\n                    $sourceRepositoryUrl: URI!,\n                    $repositoryName: String!,\n                    $continueOnError: Boolean!,\n                    $gitArchiveUrl: String,\n                    $metadataArchiveUrl: String,\n                    $accessToken: String!,\n                    $githubPat: String,\n                    $skipReleases: Boolean,\n                    $lockSource: Boolean) { \n                startRepositoryMigration(\n                    input: { \n                        sourceId: $sourceId,\n                        ownerId: $ownerId,\n                        sourceRepositoryUrl: $sourceRepositoryUrl,\n                        repositoryName: $repositoryName,\n                        continueOnError: $continueOnError,\n                        gitArchiveUrl: $gitArchiveUrl,\n                        metadataArchiveUrl: $metadataArchiveUrl,\n                        accessToken: $accessToken,\n                        githubPat: $githubPat,\n                        skipReleases: $skipReleases,\n                        lockSource: $lockSource\n                    }\n                ) {\n                    repositoryMigration {\n                        id,\n                        migrationSource {\n                            id,\n                            name,\n                            type\n                        },\n                        sourceUrl,\n                        state,\n                        failureReason\n                    }\n                  } }","variables":{"sourceId":"MS_kgDaACRmMDBiZThhNS0zMzIyLTRkYzUtODliMS03Zjg1ZjExY2E2YWU","ownerId":"O_kgDOB06WWA","sourceRepositoryUrl":"https://github.com/<ourorg>/<repo>","repositoryName":"<repo>","continueOnError":true,"gitArchiveUrl":null,"metadataArchiveUrl":null,"accessToken":"***","githubPat":"***","skipReleases":false,"lockSource":false},"operationName":"startRepositoryMigration"}
[9:16 pm] [DEBUG] GITHUB REQUEST ID: F87D:52D2:159A44C:16FBADB:63C12F79
[9:16 pm] [DEBUG] RESPONSE (BadGateway): {
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F87D:52D2:159A44C:16FBADB:63C12F79` when reporting this issue."
      }
   ]
}

[9:16 pm] [ERROR] [HTTP ERROR 502] System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OctoshiftCLI.GithubClient.SendAsync(HttpMethod httpMethod, String url, Object body, HttpStatusCode expectedStatus, Dictionary`2 customHeaders)
   at OctoshiftCLI.GithubClient.PostAsync(String url, Object body, Dictionary`2 customHeaders)
   at OctoshiftCLI.GithubApi.StartMigration(String migrationSourceId, String sourceRepoUrl, String orgId, String repo, String sourceToken, String targetToken, String gitArchiveUrl, String metadataArchiveUrl, Boolean skipReleases, Boolean lockSource)
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

As a result, not all repos were queued for migration.

**Comment by timrogers** [comment]
@testworksau Thanks for reaching out! 🙌🏻 Whilst it is possible that, in the case of a `502`, the migration could have been queued, I think it still does make sense to attempt a couple of retries.

I'd like to make sure I understand your workflow too. Are you generating a migration script, executing it to start queueing migrations, and then leaving it unattended (since queueing a large number of migrations takes a fair while!)?

@dylan-smith What do you think?

**Comment by testworksau** [comment]
Yes that's exactly what we are doing @timrogers 👍🏼

**Comment by dylan-smith** [comment]
If the migration script fails while queuing a migration I would at least expect the script to continue on with the other repos in the script, and log that one failed to queue. It looks like the script is stopping when it hits this failure to queue a migration which we should probably change to be more robust.
