### ISSUE TITLE
cipher name aes256-ctr for openssh key file is not supported

### ISSUE THREAD

**Issue by derwasp** [github/gh-gei#813]
## Description

**Version**: v. 0.32

It seems like this is the default cipher for openssh is not supported.

## Reproduction Steps

[Follow the github documentation on how to generate an ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent):

> Paste the text below, substituting in your GitHub email address.

> `$ ssh-keygen -t ed25519 -C "your_email@example.com"`

Run a command to start the export:

```
gh bbs2gh migrate-repo --bbs-server-url "https://some.repo.com" --bbs-project "YYY" --bbs-repo "AAA" --ssh-user "derwasp" --ssh-private-key "/Users/derwasp/.ssh/id_ed25519" --ssh-port 22 --github-org "AmazingOrg" --github-repo "derwasp-target-repo" --wait
```

The command fails (see the log below)

## Details

Log:

```
[11:10] [INFO] You are running the latest version of the bbs2gh extension [v0.32]
[11:10] [ERROR] Renci.SshNet.Common.SshException: cipher name aes256-ctr for openssh key file is not supported
   at Renci.SshNet.PrivateKeyFile.ParseOpenSshV1Key(Byte[] keyFileData, String passPhrase)
   at Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName)
   at OctoshiftCLI.BbsToGithub.Services.BbsSshArchiveDownloader..ctor(OctoLogger log, FileSystemProvider fileSystemProvider, String host, String sshUser, String privateKeyFileFullPath, Int32 sshPort)
   at OctoshiftCLI.BbsToGithub.BbsArchiveDownloaderFactory.CreateSshDownloader(String host, String sshUser, String privateKeyFileFullPath, Int32 sshPort, String bbsSharedHomeDirectory)
   at OctoshiftCLI.BbsToGithub.Commands.MigrateRepoCommand.BuildHandler(MigrateRepoCommandArgs args, IServiceProvider sp)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

## Links
Seems to be related to https://github.com/sshnet/SSH.NET/issues/742

## Workaround

Create a copy of the key with a supported cipher:

> `ssh-keygen -f id_ed25519_cbc -p -Z aes256-cbc`

Source: https://github.com/sshnet/SSH.NET/issues/742#issuecomment-1292945883

**Comment by ArinGhazarian** [comment]
Hi @derwasp 👋, thanks for creating this issue. 

Yes apparently SSH.NET doesn't support `aes256-ctr` cipher at this moment but there is not much we can do about it since we don't want to deviate form the main brach and have to wait until they release a new NuGet package. As you also mentioned the workaround is to force `ssh-keygen` to generate a key with `aes256-cbc` cipher:

```
 ssh-keygen -t ed25519 -Z aes256-cbc -C "your_email@example.com"
```

it may also be a good idea for us to update the documentation and suggest the above command. cc: @timrogers

**Comment by derwasp** [comment]
@ArinGhazarian thank you for such a fast response!

Indeed, until SSH.NET fixes it there's not much to do with `gei` :) The idea behind this ticket was to raise awareness and clearly state the workaround for it for the next person bumping into it.

**Comment by timrogers** [comment]
We have now updated the docs to document what ciphers are supported and what you can do to get a new keypair if yours isn't supported. 

I'm going to close this issue as I'd say that this is now working as expected - but it's great to have this issue here for anyone googling ❤️
