### ISSUE TITLE
Incorrect GHES credentials leads to "An unexpected error happened. Please see the logs for details." error

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#943]
## Description

Running `gh gei migrate-repo` from a GHES source with an incorrect access token causes the CLI to hang for a while, and leads to the following error:

> An unexpected error happened. Please see the logs for details.

Instead, we should return a descriptive error that explains that the problem is bad credentials, and that the user should check their access token.

Under the hood, we make request to the GHES server to determine its version, which `403` with a "Bad credentials" error and are repeatedly retried.

We should probably not retry these requests if they 403, and instead should bubble up the error to the user.

Here's verbose log output:

```
[11:34] [INFO] You are running the latest version of the gei CLI [v0.38]
[11:34] [INFO] Migrating Repo...
[11:34] [INFO] GITHUB SOURCE ORG: restforce
[11:34] [INFO] SOURCE REPO: ghes-test
[11:34] [INFO] GITHUB TARGET ORG: caffeine-software-sandbox
[11:34] [INFO] TARGET REPO:
[11:34] [INFO] WAIT: true
[11:34] [INFO] GHES API URL: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3
[11:34] [INFO] Using GitHub Enterprise Server - verifying server version
[11:34] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: 9e2368a7-410b-4263-be0c-ebf19bf69553
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [DEBUG] Call failed with HTTP Unauthorized, retrying...
[11:35] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: 999a3a3e-a202-4a1b-bdae-4b26804b14ee
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [DEBUG] Call failed with HTTP Unauthorized, retrying...
[11:35] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: 42066f0b-7642-4b80-806e-1e482fc01344
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [DEBUG] Call failed with HTTP Unauthorized, retrying...
[11:35] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: f81c7ed7-bf92-4ab9-869c-c8a9e26ccc69
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [DEBUG] Call failed with HTTP Unauthorized, retrying...
[11:35] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: 2972d4f2-0017-4d54-978f-cf8246e4ca37
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [DEBUG] Call failed with HTTP Unauthorized, retrying...
[11:35] [DEBUG] HTTP GET: https://timrogers-0c5065dc2d6a3aa44.ghe-test.net/api/v3/meta
[11:35] [DEBUG] GITHUB REQUEST ID: 6f19331b-eeef-4ecc-b589-db6380f568ab
[11:35] [DEBUG] RESPONSE (Unauthorized): {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
[11:35] [ERROR] [HTTP ERROR 401] System.Net.Http.HttpRequestException: GitHub API error: {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise-server@3.8/rest"}
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OctoshiftCLI.GithubClient.SendAsync(HttpMethod httpMethod, String url, Object body, HttpStatusCode expectedStatus, Dictionary`2 customHeaders)
   --- End of inner exception stack trace ---
   at OctoshiftCLI.GithubClient.SendAsync(HttpMethod httpMethod, String url, Object body, HttpStatusCode expectedStatus, Dictionary`2 customHeaders)
   at OctoshiftCLI.GithubClient.<>c__DisplayClass17_0.<<GetWithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at OctoshiftCLI.RetryPolicy.HttpRetry[T](Func`1 func, Func`2 filter)
   at OctoshiftCLI.GithubClient.GetWithRetry(String url, Dictionary`2 customHeaders, HttpStatusCode expectedStatus)
   at OctoshiftCLI.GithubClient.GetAsync(String url, Dictionary`2 customHeaders)
   at OctoshiftCLI.GithubApi.GetEnterpriseServerVersion()
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.DetermineIfBlobCredentialsRequired(MigrateRepoCommandArgs args)
   at OctoshiftCLI.GithubEnterpriseImporter.Handlers.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
   at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

## Reproduction Steps

Start a migration from a GHES instance using `gh gei migrate-repo` with an invalid access token

**Comment by dylan-smith** [comment]
I have repro'd this, and think I know what's going on. PR to follow
